path_to_save_images: '../results/results_predict'
path_to_save_result: '../results'
path_to_dataset: "D:\\projects_andrey\\cv_made_dataset\\vk-made-sports-image-classification"
path_to_classes: "D:\\projects_andrey\\cv_made_dataset\\vk-made-sports-image-classification\\encode_classes.json"
name_model: 'swin_base_patch4_window7_224'
pretrained: False
visualize_result: True
path_to_weights: "../models/checkpoint_swin_base_patch4_window7_224.pth"
img_size: [224, 224]